version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    command: ["node", "index.js"]

volumes:
  node_modules:
